amcl:
  ros__parameters:
    use_sim_time: True

map_server:
  ros__parameters:
    yaml_filename: "/home/vit/small_house.yaml"

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: True

controller_server:
  ros__parameters:
    expected_controller_frequency: 20.0
    use_sim_time: True

bt_navigator:
  ros__parameters:
    use_sim_time: True
